title = "Azure Citadel"
theme = "citadel"

languageCode = "en-gb"
DefaultContentLanguage = "en"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[menu]

  # Home -> Sections
  # menu.section appears on the Home Page under "Explore by section"
  # Side menu is controlled via frontmatter

  [[menu.section]]
    name = "About"
    url = "/about"

  [[menu.section]]
    name = "ARM Templates"
    url = "/arm"

  [[menu.section]]
    name = "Azure Policy"
    url = "/policy"

  [[menu.section]]
    name = "Packer & Ansible"
    url = "/packeransible"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "people"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 2