title = "Azure Citadel"
theme = "citadel"

[menu]

  # Home -> Sections

  [[menu.section]]
    name = "About"
    url = "/about"

  [[menu.section]]
    name = "ARM Templates"
    url = "/arm"

  [[menu.section]]
    name = "Azure Policy"
    url = "/policy"

  [[menu.section]]
    name = "Packer & Ansible"
    url = "/packeransible"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    tabWidth = 2